name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger AWS CodeBuild
        run: |
          aws codebuild start-build --project-name game-website-build 
